# Generated by Django 5.1.6 on 2025-02-13 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='forummember',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='forummember',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
